//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("The.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine zusammengesetzte Konvertierung muss aus mindestens zwei Konvertierungen bestehen..
        /// </summary>
        internal static string ErrorConcatenationMissing {
            get {
                return ResourceManager.GetString("ErrorConcatenationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Offset darf nicht null sein, da die Konvertierung sonst der Identität entspricht.
        /// </summary>
        internal static string ErrorConverterOffsetIdentity {
            get {
                return ResourceManager.GetString("ErrorConverterOffsetIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Skalierung darf nicht eins sein, da die Konvertierung sonst der Identität entspricht.
        /// </summary>
        internal static string ErrorConverterScaleIdentity {
            get {
                return ResourceManager.GetString("ErrorConverterScaleIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das angegebene Einheitensymbol &quot;{0}&quot; wurde bereits für eine andere Einheit verwendet..
        /// </summary>
        internal static string ErrorDuplicateUnitSymbol {
            get {
                return ResourceManager.GetString("ErrorDuplicateUnitSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is kein gültiges Symbol..
        /// </summary>
        internal static string ErrorInvalidUcumCiSymbol {
            get {
                return ResourceManager.GetString("ErrorInvalidUcumCiSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Minimalwert muss immer kleiner als ein Maximalwert sein..
        /// </summary>
        internal static string ErrorMinNotLessThanMax {
            get {
                return ResourceManager.GetString("ErrorMinNotLessThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der angegebene Lambda-Ausdruck hat keinen konstanten Rumpf..
        /// </summary>
        internal static string ErrorPropBodyNotConstant {
            get {
                return ResourceManager.GetString("ErrorPropBodyNotConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der angegebene Lambda-Ausdruck ist leer oder repräsentiert keine Eigenschaft..
        /// </summary>
        internal static string ErrorPropExprBodyMissing {
            get {
                return ResourceManager.GetString("ErrorPropExprBodyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Ergebnis einer Einheitskonvertierung durch Multiplikation darf nicht 0 sein, weshalb 0 als Faktor ungültig ist..
        /// </summary>
        internal static string ErrorScalingFactorDimensionless {
            get {
                return ResourceManager.GetString("ErrorScalingFactorDimensionless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Ergebnis einer Einheitskonvertierung durch Skalierung darf nicht die Identität sein, weshalb 1 als Faktor ungültig ist..
        /// </summary>
        internal static string ErrorScalingFactorIdentity {
            get {
                return ResourceManager.GetString("ErrorScalingFactorIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Ergebnis einer Einheitskonvertierung durch Addition darf nicht die Identität sein, weshalb 0 als Offset ungültig ist..
        /// </summary>
        internal static string ErrorShiftingOffsetIdentity {
            get {
                return ResourceManager.GetString("ErrorShiftingOffsetIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Faktor in einer durch Skalierung entstandenen Einheit darf nicht dimensionslos sein, weshalb 0 nicht als Skalierungsfaktor oder Exponent verwendet werden darf..
        /// </summary>
        internal static string ErrorUnitFactorDimensionless {
            get {
                return ResourceManager.GetString("ErrorUnitFactorDimensionless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string ErrorUnitFactorIdentity {
            get {
                return ResourceManager.GetString("ErrorUnitFactorIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Acre.
        /// </summary>
        internal static string ImperialUnitAcre {
            get {
                return ResourceManager.GetString("ImperialUnitAcre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Cable.
        /// </summary>
        internal static string ImperialUnitCable {
            get {
                return ResourceManager.GetString("ImperialUnitCable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Chain.
        /// </summary>
        internal static string ImperialUnitChain {
            get {
                return ResourceManager.GetString("ImperialUnitChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Dram.
        /// </summary>
        internal static string ImperialUnitDrachm {
            get {
                return ResourceManager.GetString("ImperialUnitDrachm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Fathom.
        /// </summary>
        internal static string ImperialUnitFathom {
            get {
                return ResourceManager.GetString("ImperialUnitFathom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Fluid Drachm.
        /// </summary>
        internal static string ImperialUnitFluidDrachm {
            get {
                return ResourceManager.GetString("ImperialUnitFluidDrachm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britische Fluid Ounce.
        /// </summary>
        internal static string ImperialUnitFluidOunce {
            get {
                return ResourceManager.GetString("ImperialUnitFluidOunce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Fluid Scruple.
        /// </summary>
        internal static string ImperialUnitFluidScruple {
            get {
                return ResourceManager.GetString("ImperialUnitFluidScruple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britischer Fuß.
        /// </summary>
        internal static string ImperialUnitFoot {
            get {
                return ResourceManager.GetString("ImperialUnitFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Furlong.
        /// </summary>
        internal static string ImperialUnitFurlong {
            get {
                return ResourceManager.GetString("ImperialUnitFurlong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britische Gallone.
        /// </summary>
        internal static string ImperialUnitGallon {
            get {
                return ResourceManager.GetString("ImperialUnitGallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Gill.
        /// </summary>
        internal static string ImperialUnitGill {
            get {
                return ResourceManager.GetString("ImperialUnitGill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Grain.
        /// </summary>
        internal static string ImperialUnitGrain {
            get {
                return ResourceManager.GetString("ImperialUnitGrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Hundredweight.
        /// </summary>
        internal static string ImperialUnitHundredweight {
            get {
                return ResourceManager.GetString("ImperialUnitHundredweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Zoll.
        /// </summary>
        internal static string ImperialUnitInch {
            get {
                return ResourceManager.GetString("ImperialUnitInch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britische League.
        /// </summary>
        internal static string ImperialUnitLeague {
            get {
                return ResourceManager.GetString("ImperialUnitLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Link.
        /// </summary>
        internal static string ImperialUnitLink {
            get {
                return ResourceManager.GetString("ImperialUnitLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britische Meile.
        /// </summary>
        internal static string ImperialUnitMile {
            get {
                return ResourceManager.GetString("ImperialUnitMile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Minim.
        /// </summary>
        internal static string ImperialUnitMinim {
            get {
                return ResourceManager.GetString("ImperialUnitMinim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britische nautische Meile.
        /// </summary>
        internal static string ImperialUnitNauticalMile {
            get {
                return ResourceManager.GetString("ImperialUnitNauticalMile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britische Unze.
        /// </summary>
        internal static string ImperialUnitOunce {
            get {
                return ResourceManager.GetString("ImperialUnitOunce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Perch.
        /// </summary>
        internal static string ImperialUnitPerch {
            get {
                return ResourceManager.GetString("ImperialUnitPerch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Pint.
        /// </summary>
        internal static string ImperialUnitPint {
            get {
                return ResourceManager.GetString("ImperialUnitPint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Pfund.
        /// </summary>
        internal static string ImperialUnitPound {
            get {
                return ResourceManager.GetString("ImperialUnitPound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Quart.
        /// </summary>
        internal static string ImperialUnitQuart {
            get {
                return ResourceManager.GetString("ImperialUnitQuart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Quarter.
        /// </summary>
        internal static string ImperialUnitQuarter {
            get {
                return ResourceManager.GetString("ImperialUnitQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Rod.
        /// </summary>
        internal static string ImperialUnitRod {
            get {
                return ResourceManager.GetString("ImperialUnitRod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Rood.
        /// </summary>
        internal static string ImperialUnitRood {
            get {
                return ResourceManager.GetString("ImperialUnitRood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Stone.
        /// </summary>
        internal static string ImperialUnitStone {
            get {
                return ResourceManager.GetString("ImperialUnitStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Thou.
        /// </summary>
        internal static string ImperialUnitThou {
            get {
                return ResourceManager.GetString("ImperialUnitThou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britische Tonne.
        /// </summary>
        internal static string ImperialUnitTon {
            get {
                return ResourceManager.GetString("ImperialUnitTon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Britisches Yard.
        /// </summary>
        internal static string ImperialUnitYard {
            get {
                return ResourceManager.GetString("ImperialUnitYard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celsius.
        /// </summary>
        internal static string MetricUnitCelsius {
            get {
                return ResourceManager.GetString("MetricUnitCelsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zentiliter.
        /// </summary>
        internal static string MetricUnitCentilitre {
            get {
                return ResourceManager.GetString("MetricUnitCentilitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liter.
        /// </summary>
        internal static string MetricUnitLitre {
            get {
                return ResourceManager.GetString("MetricUnitLitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliliter.
        /// </summary>
        internal static string MetricUnitMillilitre {
            get {
                return ResourceManager.GetString("MetricUnitMillilitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonne.
        /// </summary>
        internal static string MetricUnitTonne {
            get {
                return ResourceManager.GetString("MetricUnitTonne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atto.
        /// </summary>
        internal static string SiPrefixAtto {
            get {
                return ResourceManager.GetString("SiPrefixAtto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zenti.
        /// </summary>
        internal static string SiPrefixCenti {
            get {
                return ResourceManager.GetString("SiPrefixCenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deka.
        /// </summary>
        internal static string SiPrefixDeca {
            get {
                return ResourceManager.GetString("SiPrefixDeca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dezi.
        /// </summary>
        internal static string SiPrefixDeci {
            get {
                return ResourceManager.GetString("SiPrefixDeci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exa.
        /// </summary>
        internal static string SiPrefixExa {
            get {
                return ResourceManager.GetString("SiPrefixExa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femto.
        /// </summary>
        internal static string SiPrefixFemto {
            get {
                return ResourceManager.GetString("SiPrefixFemto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giga.
        /// </summary>
        internal static string SiPrefixGiga {
            get {
                return ResourceManager.GetString("SiPrefixGiga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hekto.
        /// </summary>
        internal static string SiPrefixHecto {
            get {
                return ResourceManager.GetString("SiPrefixHecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilo.
        /// </summary>
        internal static string SiPrefixKilo {
            get {
                return ResourceManager.GetString("SiPrefixKilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mega.
        /// </summary>
        internal static string SiPrefixMega {
            get {
                return ResourceManager.GetString("SiPrefixMega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikro.
        /// </summary>
        internal static string SiPrefixMicro {
            get {
                return ResourceManager.GetString("SiPrefixMicro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milli.
        /// </summary>
        internal static string SiPrefixMilli {
            get {
                return ResourceManager.GetString("SiPrefixMilli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nano.
        /// </summary>
        internal static string SiPrefixNano {
            get {
                return ResourceManager.GetString("SiPrefixNano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peta.
        /// </summary>
        internal static string SiPrefixPeta {
            get {
                return ResourceManager.GetString("SiPrefixPeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piko.
        /// </summary>
        internal static string SiPrefixPico {
            get {
                return ResourceManager.GetString("SiPrefixPico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tera.
        /// </summary>
        internal static string SiPrefixTera {
            get {
                return ResourceManager.GetString("SiPrefixTera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yokto.
        /// </summary>
        internal static string SiPrefixYocto {
            get {
                return ResourceManager.GetString("SiPrefixYocto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yotta.
        /// </summary>
        internal static string SiPrefixYotta {
            get {
                return ResourceManager.GetString("SiPrefixYotta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zepto.
        /// </summary>
        internal static string SiPrefixZepto {
            get {
                return ResourceManager.GetString("SiPrefixZepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zetta.
        /// </summary>
        internal static string SiPrefixZetta {
            get {
                return ResourceManager.GetString("SiPrefixZetta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ampere.
        /// </summary>
        internal static string SiUnitAmpere {
            get {
                return ResourceManager.GetString("SiUnitAmpere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Becquerel.
        /// </summary>
        internal static string SiUnitBecquerel {
            get {
                return ResourceManager.GetString("SiUnitBecquerel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candela.
        /// </summary>
        internal static string SiUnitCandela {
            get {
                return ResourceManager.GetString("SiUnitCandela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coulomb.
        /// </summary>
        internal static string SiUnitCoulomb {
            get {
                return ResourceManager.GetString("SiUnitCoulomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kubikmeter.
        /// </summary>
        internal static string SiUnitCubicMetre {
            get {
                return ResourceManager.GetString("SiUnitCubicMetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensionslos.
        /// </summary>
        internal static string SiUnitDimensionless {
            get {
                return ResourceManager.GetString("SiUnitDimensionless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farad.
        /// </summary>
        internal static string SiUnitFarad {
            get {
                return ResourceManager.GetString("SiUnitFarad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gramm.
        /// </summary>
        internal static string SiUnitGramme {
            get {
                return ResourceManager.GetString("SiUnitGramme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        internal static string SiUnitGray {
            get {
                return ResourceManager.GetString("SiUnitGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Henry.
        /// </summary>
        internal static string SiUnitHenry {
            get {
                return ResourceManager.GetString("SiUnitHenry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hertz.
        /// </summary>
        internal static string SiUnitHertz {
            get {
                return ResourceManager.GetString("SiUnitHertz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joule.
        /// </summary>
        internal static string SiUnitJoule {
            get {
                return ResourceManager.GetString("SiUnitJoule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katal.
        /// </summary>
        internal static string SiUnitKatal {
            get {
                return ResourceManager.GetString("SiUnitKatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelvin.
        /// </summary>
        internal static string SiUnitKelvin {
            get {
                return ResourceManager.GetString("SiUnitKelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilogramm.
        /// </summary>
        internal static string SiUnitKilogramme {
            get {
                return ResourceManager.GetString("SiUnitKilogramme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lumen.
        /// </summary>
        internal static string SiUnitLumen {
            get {
                return ResourceManager.GetString("SiUnitLumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lux.
        /// </summary>
        internal static string SiUnitLux {
            get {
                return ResourceManager.GetString("SiUnitLux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        internal static string SiUnitMetre {
            get {
                return ResourceManager.GetString("SiUnitMetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mol.
        /// </summary>
        internal static string SiUnitMole {
            get {
                return ResourceManager.GetString("SiUnitMole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newton.
        /// </summary>
        internal static string SiUnitNewton {
            get {
                return ResourceManager.GetString("SiUnitNewton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohm.
        /// </summary>
        internal static string SiUnitOhm {
            get {
                return ResourceManager.GetString("SiUnitOhm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pascal.
        /// </summary>
        internal static string SiUnitPascal {
            get {
                return ResourceManager.GetString("SiUnitPascal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radian.
        /// </summary>
        internal static string SiUnitRadian {
            get {
                return ResourceManager.GetString("SiUnitRadian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekunde.
        /// </summary>
        internal static string SiUnitSecond {
            get {
                return ResourceManager.GetString("SiUnitSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siemens.
        /// </summary>
        internal static string SiUnitSiemens {
            get {
                return ResourceManager.GetString("SiUnitSiemens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sievert.
        /// </summary>
        internal static string SiUnitSievert {
            get {
                return ResourceManager.GetString("SiUnitSievert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadratmeter.
        /// </summary>
        internal static string SiUnitSquareMetre {
            get {
                return ResourceManager.GetString("SiUnitSquareMetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steradian.
        /// </summary>
        internal static string SiUnitSteradian {
            get {
                return ResourceManager.GetString("SiUnitSteradian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tesla.
        /// </summary>
        internal static string SiUnitTesla {
            get {
                return ResourceManager.GetString("SiUnitTesla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volt.
        /// </summary>
        internal static string SiUnitVolt {
            get {
                return ResourceManager.GetString("SiUnitVolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watt.
        /// </summary>
        internal static string SiUnitWatt {
            get {
                return ResourceManager.GetString("SiUnitWatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weber.
        /// </summary>
        internal static string SiUnitWeber {
            get {
                return ResourceManager.GetString("SiUnitWeber", resourceCulture);
            }
        }
    }
}
