#if defined(_WIN32)
#pragma warning (disable : 4786)
#endif

/**
 ** Us this define to create a .hpp file compatible with the c++ compiler of visual studio 2005
 **/
#define VIS_MSVC8CPP_EXT 1

#include <stdio.h>
#include <string.h>
#include <string>
#include <vector>
#include <stdlib.h>
#ifdef _WIN32
#include <windows.h>
#else
#include <ctype.h>
#endif
#include <GL/gl.h>
#ifdef _WIN32
#include <GL/wglext.h>
#else
#include <GL/glx.h>
#include "GL/glxext.h"
#endif
#define GLH_EXT_SINGLE_FILE

#define GLH_NAMESPACE_GL   1
#define GLH_NAMESPACE_WGL  2
#define GLH_NAMESPACE_GLX  3

int GetToken(FILE *fpInput, char* token) {
	return fscanf(fpInput, "%s", token);
}

int GetNamespace(const char * token) {
	if(strstr(token, "wgl")) return GLH_NAMESPACE_WGL;
	if(strstr(token, "glX")) return GLH_NAMESPACE_GLX;
	return GLH_NAMESPACE_GL;
}

FILE* OpenFile(const char* filename, const char* perms) {
	FILE *fp;
	fp = fopen(filename, perms);
	if (NULL == fp) {
		printf("ERROR: could not open %s\n", filename);
		exit(-1);
	}
	return fp;
}

int ParseFile(FILE *fpInput, FILE *fpOutput, int header, int footer, int mvscpp) {
    std::string currentExtension;
    std::vector<std::string> gl12extensions;
    std::vector<std::string> gl13extensions;
    std::vector<std::string> gl14extensions;
    std::vector<std::string> gl15extensions;
    std::vector<std::string> gl20extensions;
    std::vector<std::string> gl21extensions;
    std::vector<std::string> gl30extensions;
    std::vector<std::string> gl31extensions;
    std::vector<std::string> gl32extensions;
    std::vector<std::string> gl33extensions;
    std::vector<std::string> gl40extensions;
    std::vector<std::string> gl41extensions;

    int i;
	char token[256];
	char uprToken[256];
	int tokenNamespace;
	int opengl_core_names;
	char *name_macro;

#ifndef VIS_MSVC8CPP_EXT 
	mvscpp = 0; /* paranoia-clearance */
#endif /* VIS_MSVC8CPP_EXT */

	if (footer) {
		fprintf(fpOutput, "#ifndef _WIN32\n");	    	
	}
	if (!header) {
		/** changes are made in this block */
		fprintf(fpOutput, "#ifdef GLH_EXT_SINGLE_FILE\n");
		fprintf(fpOutput, "\n");
		fprintf(fpOutput, "int glh_init_extension(const char* extension)\n");
		fprintf(fpOutput, "{\n");
		fprintf(fpOutput, "    if (NULL == extension) {\n");
		fprintf(fpOutput, "        return GL_FALSE;\n");
		fprintf(fpOutput, "#ifndef _WIN32\n");
		if (mvscpp) { // text for the .hpp
			// smaller change for more consistency
			fprintf(fpOutput, "    }\n");
			fprintf(fpOutput, "    if (0 == strcmp (extension, \"GL_VERSION_1_2\") || 0 == strcmp (extension, \"GL_VERSION_1_3\") || 0 == strcmp (extension, \"GL_VERSION_1_4\")) {\n");
		} else {
			fprintf(fpOutput, "    } else if (0 == strcmp (extension, \"GL_VERSION_1_2\") || 0 == strcmp (extension, \"GL_VERSION_1_3\") || 0 == strcmp (extension, \"GL_VERSION_1_4\")) {\n");
		}
		fprintf(fpOutput, "        return GL_TRUE;\n");
		fprintf(fpOutput, "#endif\n");
		/** changes are made in this block */

	} else if (!footer) {
	    
		fprintf(fpOutput, "/* File generated by extgen.cpp -- do not modify */\n");

		fprintf(fpOutput, "#ifndef GLH_GENEXT_H\n");
		fprintf(fpOutput, "#define GLH_GENEXT_H\n\n");
		fprintf(fpOutput, "#ifdef __cplusplus\n");
		fprintf(fpOutput, "extern \"C\" {\n");
   		fprintf(fpOutput, "#endif\n\n");
   		fprintf(fpOutput, "#ifdef __gl_h_\n");
   		fprintf(fpOutput, "#error \"gl.h must not be included before glh_genext.h due to broken linux opengl headers\"\n");
   		fprintf(fpOutput, "#endif\n");

   		fprintf(fpOutput, "#ifdef __glext_h_\n");
   		fprintf(fpOutput, "#error \"glext.h must not be included before glh_genext.h due to broken linux opengl headers\"\n");
   		fprintf(fpOutput, "#endif\n");

   		fprintf(fpOutput, "/*\n");
   		fprintf(fpOutput, "* Define this token if you want \"old-style\" header file behaviour (extensions\n");
   		fprintf(fpOutput, "* defined in gl.h).  Otherwise, extensions will be included from glext.h.\n");
    	fprintf(fpOutput, "*/\n");
   		fprintf(fpOutput, "#define GL_GLEXT_LEGACY\n");
		fprintf(fpOutput, "#include <GL/gl.h>\n");
		fprintf(fpOutput, "#ifndef _WIN32\n");
		fprintf(fpOutput, "#undef GL_VERSION_1_1\n");
		fprintf(fpOutput, "#undef GL_VERSION_1_2\n");
		fprintf(fpOutput, "#undef GL_VERSION_1_3\n");
		fprintf(fpOutput, "#undef GL_VERSION_1_4\n");
		fprintf(fpOutput, "#endif\n");
		fprintf(fpOutput, "#include \"GL/glext.h\"\n");
		fprintf(fpOutput, "#if defined(WIN32)\n");
		fprintf(fpOutput, "#  include <GL/wglext.h>\n");
		fprintf(fpOutput, "#  define GLH_EXT_GET_PROC_ADDRESS(p)   wglGetProcAddress(p) \n");
		fprintf(fpOutput, "#elif defined(UNIX)\n");
		fprintf(fpOutput, "#  include <string.h>\n");
		fprintf(fpOutput, "#  include <GL/glx.h>\n");
		fprintf(fpOutput, "#  include <GL/glxext.h>\n");
		fprintf(fpOutput, "#  define GLH_EXT_GET_PROC_ADDRESS(p)   glXGetProcAddressARB( (const GLubyte *) p) \n");
		fprintf(fpOutput, "#endif\n\n");

		fprintf(fpOutput, "#ifdef GLH_EXT_SINGLE_FILE\n");
		fprintf(fpOutput, "#  ifdef _WIN32\n");
		fprintf(fpOutput, "#      define GLH_EXTERN _declspec(dllexport)\n");
		fprintf(fpOutput, "#  else\n");
		fprintf(fpOutput, "#      define GLH_EXTERN\n");
		fprintf(fpOutput, "#  endif\n");
		fprintf(fpOutput, "#  define GLH_INITIALIZER = 0\n");
		fprintf(fpOutput, "#else\n");
		fprintf(fpOutput, "#  if defined(_WIN32) && defined(GLH_EXT_IMPORT)\n");
		fprintf(fpOutput, "#      define GLH_EXTERN _declspec(dllimport) extern\n");
		fprintf(fpOutput, "#  else\n");
		fprintf(fpOutput, "#      define GLH_EXTERN extern\n");
		fprintf(fpOutput, "#  endif\n");
		fprintf(fpOutput, "#  define GLH_INITIALIZER\n");
		fprintf(fpOutput, "#endif\n\n");

        fprintf(fpOutput, "#define GLH__PREPROCESSOR_GYMNASTICS2(a,b) a##b\n");
		fprintf(fpOutput, "#define GLH__PREPROCESSOR_GYMNASTICS(a,b) GLH__PREPROCESSOR_GYMNASTICS2(a,b)\n\n");
		fprintf (fpOutput, "#ifndef _WIN32\n");
		fprintf (fpOutput, "#define GLH_EXT_PREFIX _\n");
		fprintf (fpOutput, "#endif\n");
		

		fprintf(fpOutput, "#ifndef GLH_EXT_PREFIX\n");
		fprintf(fpOutput, "# define GLH_EXT_NAME(a) a\n");
		fprintf(fpOutput, "#else\n");
		fprintf(fpOutput, "# define GLH_EXT_NAME(a) GLH__PREPROCESSOR_GYMNASTICS(GLH_EXT_PREFIX,a)\n");
		fprintf(fpOutput, "#endif\n\n");

		fprintf(fpOutput, "#ifndef _WIN32\n");
		fprintf(fpOutput, "# ifndef GLH_CORE_PREFIX\n");
		fprintf(fpOutput, "#  define GLH_CORE_PREFIX _\n");
		fprintf(fpOutput, "# endif\n");
		fprintf(fpOutput, "#endif\n\n");

		fprintf(fpOutput, "#ifndef GLH_CORE_PREFIX\n");
		fprintf(fpOutput, "# define GLH_CORE_NAME(a) a\n");
		fprintf(fpOutput, "#else\n");
		fprintf(fpOutput, "# define GLH_CORE_NAME(a) GLH__PREPROCESSOR_GYMNASTICS(GLH_CORE_PREFIX,a)\n");
		fprintf(fpOutput, "#endif\n\n");



	}


A:
	if (GetToken(fpInput, token) == EOF) goto FIN;
	if (0 == strcmp(token, "GL_VERSION_1_2") ||
	    0 == strcmp(token, "GL_VERSION_1_3") ||
	    0 == strcmp(token, "GL_VERSION_1_4") ||
	    0 == strcmp(token, "GL_VERSION_1_5") ||
	    0 == strcmp(token, "GL_VERSION_2_0") ||
        0 == strcmp(token, "GL_VERSION_2_1") ||
        0 == strcmp(token, "GL_VERSION_3_0") ||
        0 == strcmp(token, "GL_VERSION_3_1") ||
        0 == strcmp(token, "GL_VERSION_3_2") ||
        0 == strcmp(token, "GL_VERSION_3_3") ||
	    0 == strcmp(token, "GL_VERSION_4_0") ||
        0 == strcmp(token, "GL_VERSION_4_1")) {
		opengl_core_names = 1;
		name_macro = "GLH_CORE_NAME";
	} else {
		opengl_core_names = 0;
		name_macro = "GLH_EXT_NAME";
	}
	/* obsolete?
	if (opengl_core_names>0) {
	    fprintf (fpOutput, "#ifdef _WIN32\n");
	}
	*/
	
    if (0 == strcmp(token, "GL_VERSION_1_2")) {
	    fprintf(fpOutput, "#if defined(GL_VERSION_1_2) || "
		                  "defined(GL_VERSION_1_3) || defined(GL_VERSION_1_4) || "
		                  "defined(GL_VERSION_1_5) || defined(GL_VERSION_2_0) || "
                          "defined(GL_VERSION_2_1) || defined(GL_VERSION_3_0) || "
                          "defined(GL_VERSION_3_1) || defined(GL_VERSION_3_2) || "
                          "defined(GL_VERSION_3_3) || defined(GL_VERSION_4_0) || "
		                  "defined(GL_VERSION_4_1)\n");
	} else if (0 == strcmp(token, "GL_VERSION_1_3")) {
	    fprintf(fpOutput, "#if defined(GL_VERSION_1_3) || defined(GL_VERSION_1_4) || "
		                  "defined(GL_VERSION_1_5) || defined(GL_VERSION_2_0) || "
		                  "defined(GL_VERSION_2_1) || defined(GL_VERSION_3_0) || "
                          "defined(GL_VERSION_3_1) || defined(GL_VERSION_3_2) || "
                          "defined(GL_VERSION_3_3) || defined(GL_VERSION_4_0) || "
		                  "defined(GL_VERSION_4_1)\n");
	} else if (0 == strcmp(token, "GL_VERSION_1_4")) {
	    fprintf(fpOutput, "#if defined(GL_VERSION_1_4) || "
		                  "defined(GL_VERSION_1_5) || defined(GL_VERSION_2_0) || "
		                  "defined(GL_VERSION_2_1) || defined(GL_VERSION_3_0) || "
                          "defined(GL_VERSION_3_1) || defined(GL_VERSION_3_2) || "
                          "defined(GL_VERSION_3_3) || defined(GL_VERSION_4_0) || "
		                  "defined(GL_VERSION_4_1)\n");
	} else if (0 == strcmp(token, "GL_VERSION_1_5")) {
	    fprintf(fpOutput, "#if defined(GL_VERSION_1_5) || "
		                  "defined(GL_VERSION_2_0) || "
		                  "defined(GL_VERSION_2_1) || defined(GL_VERSION_3_0) || "
                          "defined(GL_VERSION_3_1) || defined(GL_VERSION_3_2) || "
                          "defined(GL_VERSION_3_3) || defined(GL_VERSION_4_0) || "
		                  "defined(GL_VERSION_4_1)\n");
	} else if (0 == strcmp(token, "GL_VERSION_2_0")) {
	    fprintf(fpOutput, "#if defined(GL_VERSION_2_0) || "
		                  "defined(GL_VERSION_2_1) || defined(GL_VERSION_3_0) || "
                          "defined(GL_VERSION_3_1) || defined(GL_VERSION_3_2) || "
                          "defined(GL_VERSION_3_3) || defined(GL_VERSION_4_0) || "
		                  "defined(GL_VERSION_4_1)\n");
	} else if (0 == strcmp(token, "GL_VERSION_2_1")) {
	    fprintf(fpOutput, "#if defined(GL_VERSION_2_1) || "
                          "defined(GL_VERSION_3_0) || "
                          "defined(GL_VERSION_3_1) || defined(GL_VERSION_3_2) || "
                          "defined(GL_VERSION_3_3) || defined(GL_VERSION_4_0) || "
		                  "defined(GL_VERSION_4_1)\n");
    } else if (0 == strcmp(token, "GL_VERSION_3_0")) {
	    fprintf(fpOutput, "#if defined(GL_VERSION_3_0) || "
                          "defined(GL_VERSION_3_1) || defined(GL_VERSION_3_2) || "
                          "defined(GL_VERSION_3_3) || defined(GL_VERSION_4_0) || "
		                  "defined(GL_VERSION_4_1)\n");
    } else if (0 == strcmp(token, "GL_VERSION_3_1")) {
	    fprintf(fpOutput, "#if defined(GL_VERSION_3_1) || defined(GL_VERSION_3_2) || "
                          "defined(GL_VERSION_3_3) || defined(GL_VERSION_4_0) || "
		                  "defined(GL_VERSION_4_1)\n");
    } else if (0 == strcmp(token, "GL_VERSION_3_2")) {
	    fprintf(fpOutput, "#if defined(GL_VERSION_3_2) || "
                          "defined(GL_VERSION_3_3) || defined(GL_VERSION_4_0) || "
		                  "defined(GL_VERSION_4_1)\n");
    } else if (0 == strcmp(token, "GL_VERSION_3_3")) {
	    fprintf(fpOutput, "#if defined(GL_VERSION_3_3) || defined(GL_VERSION_4_0) || "
		                  "defined(GL_VERSION_4_1)\n");
    } else if (0 == strcmp(token, "GL_VERSION_4_0")) {
	    fprintf(fpOutput, "#if defined(GL_VERSION_4_0) || defined(GL_VERSION_4_1)\n");
    } else if (0 == strcmp(token, "GL_VERSION_4_1")) {
	    fprintf(fpOutput, "#if defined(GL_VERSION_4_1)\n");
	} else {
        fprintf(fpOutput, "#ifdef %s\n", token);
	}
    
	if (!header) {
		/** changes are made in this block */
        currentExtension = token;

		if (mvscpp) {
			fprintf(fpOutput, "    }\n");
			fprintf(fpOutput, "    if (0 == strcmp(extension, \"%s\")) {\n", token);
		} else { /* if (mvscpp) */
			fprintf(fpOutput, "    } else if (0 == strcmp(extension, \"%s\")) {\n", token);
		} /* if (mvscpp) */

        if (currentExtension == "GL_VERSION_1_3" || 
		    currentExtension == "GL_VERSION_1_4" ||
		    currentExtension == "GL_VERSION_1_5" ||
		    currentExtension == "GL_VERSION_2_0" ||
            currentExtension == "GL_VERSION_2_1" ||
            currentExtension == "GL_VERSION_3_0" ||
            currentExtension == "GL_VERSION_3_1" ||
            currentExtension == "GL_VERSION_3_2" ||
            currentExtension == "GL_VERSION_3_3" ||
            currentExtension == "GL_VERSION_4_0" ||
		    currentExtension == "GL_VERSION_4_1")
        {
            for (unsigned int i = 0; i < gl12extensions.size(); i++)
            {
                std::string curFunc = gl12extensions[i];
                std::string funcUp = curFunc;
                for (unsigned int n = 0; n < funcUp.length(); n++) funcUp[n] = toupper(funcUp[n]);
    		    fprintf(fpOutput, "        %s(%s) = (PFN%sPROC)GLH_EXT_GET_PROC_ADDRESS(\"%s\");\n", name_macro, curFunc.c_str(), funcUp.c_str(), curFunc.c_str());
	        	fprintf(fpOutput, "        if (NULL == %s(%s))\n", name_macro, curFunc.c_str());
    	    	fprintf(fpOutput, "            return GL_FALSE;\n");
            }
        }
       
        if (currentExtension == "GL_VERSION_1_4" ||
		    currentExtension == "GL_VERSION_1_5" ||
		    currentExtension == "GL_VERSION_2_0" ||
		    currentExtension == "GL_VERSION_2_1" ||
            currentExtension == "GL_VERSION_3_0" ||
            currentExtension == "GL_VERSION_3_1" ||
            currentExtension == "GL_VERSION_3_2" ||
            currentExtension == "GL_VERSION_3_3" ||
            currentExtension == "GL_VERSION_4_0" ||
		    currentExtension == "GL_VERSION_4_1")
        {
            for (unsigned int i = 0; i < gl13extensions.size(); i++)
            {
                std::string curFunc = gl13extensions[i];
                std::string funcUp = curFunc;
                for (unsigned int n = 0; n < funcUp.length(); n++) funcUp[n] = toupper(funcUp[n]);
    		    fprintf(fpOutput, "        %s(%s) = (PFN%sPROC)GLH_EXT_GET_PROC_ADDRESS(\"%s\");\n", name_macro, curFunc.c_str(), funcUp.c_str(), curFunc.c_str());
	        	fprintf(fpOutput, "        if (NULL == %s(%s))\n", name_macro, curFunc.c_str());
    	    	fprintf(fpOutput, "            return GL_FALSE;\n");
            }
        }
        if (currentExtension == "GL_VERSION_1_5" ||
		    currentExtension == "GL_VERSION_2_0" ||
		    currentExtension == "GL_VERSION_2_1" ||
            currentExtension == "GL_VERSION_3_0" ||
            currentExtension == "GL_VERSION_3_1" ||
            currentExtension == "GL_VERSION_3_2" ||
            currentExtension == "GL_VERSION_3_3" ||
            currentExtension == "GL_VERSION_4_0" ||
		    currentExtension == "GL_VERSION_4_1")
        {
            for (unsigned int i = 0; i < gl14extensions.size(); i++)
            {
                std::string curFunc = gl14extensions[i];
                std::string funcUp = curFunc;
                for (unsigned int n = 0; n < funcUp.length(); n++) funcUp[n] = toupper(funcUp[n]);
    		    fprintf(fpOutput, "        %s(%s) = (PFN%sPROC)GLH_EXT_GET_PROC_ADDRESS(\"%s\");\n", name_macro, curFunc.c_str(), funcUp.c_str(), curFunc.c_str());
	        	fprintf(fpOutput, "        if (NULL == %s(%s))\n", name_macro, curFunc.c_str());
    	    	fprintf(fpOutput, "            return GL_FALSE;\n");
            }
        }
        if (currentExtension == "GL_VERSION_2_0" ||
		    currentExtension == "GL_VERSION_2_1" ||
            currentExtension == "GL_VERSION_3_0" ||
            currentExtension == "GL_VERSION_3_1" ||
            currentExtension == "GL_VERSION_3_2" ||
            currentExtension == "GL_VERSION_3_3" ||
            currentExtension == "GL_VERSION_4_0" ||
		    currentExtension == "GL_VERSION_4_1")
        {
            for (unsigned int i = 0; i < gl15extensions.size(); i++)
            {
                std::string curFunc = gl15extensions[i];
                std::string funcUp = curFunc;
                for (unsigned int n = 0; n < funcUp.length(); n++) funcUp[n] = toupper(funcUp[n]);
    		    fprintf(fpOutput, "        %s(%s) = (PFN%sPROC)GLH_EXT_GET_PROC_ADDRESS(\"%s\");\n", name_macro, curFunc.c_str(), funcUp.c_str(), curFunc.c_str());
	        	fprintf(fpOutput, "        if (NULL == %s(%s))\n", name_macro, curFunc.c_str());
    	    	fprintf(fpOutput, "            return GL_FALSE;\n");
            }
        }
        if (currentExtension == "GL_VERSION_2_1" ||
            currentExtension == "GL_VERSION_3_0" ||
            currentExtension == "GL_VERSION_3_1" ||
            currentExtension == "GL_VERSION_3_2" ||
            currentExtension == "GL_VERSION_3_3" ||
            currentExtension == "GL_VERSION_4_0" ||
		    currentExtension == "GL_VERSION_4_1")
        {
            for (unsigned int i = 0; i < gl20extensions.size(); i++)
            {
                std::string curFunc = gl20extensions[i];
                std::string funcUp = curFunc;
                for (unsigned int n = 0; n < funcUp.length(); n++) funcUp[n] = toupper(funcUp[n]);
    		    fprintf(fpOutput, "        %s(%s) = (PFN%sPROC)GLH_EXT_GET_PROC_ADDRESS(\"%s\");\n", name_macro, curFunc.c_str(), funcUp.c_str(), curFunc.c_str());
	        	fprintf(fpOutput, "        if (NULL == %s(%s))\n", name_macro, curFunc.c_str());
    	    	fprintf(fpOutput, "            return GL_FALSE;\n");
            }
        }
        if (currentExtension == "GL_VERSION_3_0" ||
            currentExtension == "GL_VERSION_3_1" ||
            currentExtension == "GL_VERSION_3_2" ||
            currentExtension == "GL_VERSION_3_3" ||
            currentExtension == "GL_VERSION_4_0" ||
		    currentExtension == "GL_VERSION_4_1")
        {
            for (unsigned int i = 0; i < gl21extensions.size(); i++)
            {
                std::string curFunc = gl21extensions[i];
                std::string funcUp = curFunc;
                for (unsigned int n = 0; n < funcUp.length(); n++) funcUp[n] = toupper(funcUp[n]);
    		    fprintf(fpOutput, "        %s(%s) = (PFN%sPROC)GLH_EXT_GET_PROC_ADDRESS(\"%s\");\n", name_macro, curFunc.c_str(), funcUp.c_str(), curFunc.c_str());
	        	fprintf(fpOutput, "        if (NULL == %s(%s))\n", name_macro, curFunc.c_str());
    	    	fprintf(fpOutput, "            return GL_FALSE;\n");
            }
        }
		if (currentExtension == "GL_VERSION_3_1" ||
            currentExtension == "GL_VERSION_3_2" ||
            currentExtension == "GL_VERSION_3_3" ||
            currentExtension == "GL_VERSION_4_0" ||
		    currentExtension == "GL_VERSION_4_1")
        {
            for (unsigned int i = 0; i < gl30extensions.size(); i++)
            {
                std::string curFunc = gl30extensions[i];
                std::string funcUp = curFunc;
                for (unsigned int n = 0; n < funcUp.length(); n++) funcUp[n] = toupper(funcUp[n]);
    		    fprintf(fpOutput, "        %s(%s) = (PFN%sPROC)GLH_EXT_GET_PROC_ADDRESS(\"%s\");\n", name_macro, curFunc.c_str(), funcUp.c_str(), curFunc.c_str());
	        	fprintf(fpOutput, "        if (NULL == %s(%s))\n", name_macro, curFunc.c_str());
    	    	fprintf(fpOutput, "            return GL_FALSE;\n");
            }
        }
        if (currentExtension == "GL_VERSION_3_2" ||
            currentExtension == "GL_VERSION_3_3" ||
            currentExtension == "GL_VERSION_4_0" ||
		    currentExtension == "GL_VERSION_4_1")
        {
            for (unsigned int i = 0; i < gl31extensions.size(); i++)
            {
                std::string curFunc = gl31extensions[i];
                std::string funcUp = curFunc;
                for (unsigned int n = 0; n < funcUp.length(); n++) funcUp[n] = toupper(funcUp[n]);
    		    fprintf(fpOutput, "        %s(%s) = (PFN%sPROC)GLH_EXT_GET_PROC_ADDRESS(\"%s\");\n", name_macro, curFunc.c_str(), funcUp.c_str(), curFunc.c_str());
	        	fprintf(fpOutput, "        if (NULL == %s(%s))\n", name_macro, curFunc.c_str());
    	    	fprintf(fpOutput, "            return GL_FALSE;\n");
            }
        }
        if (currentExtension == "GL_VERSION_3_3" ||
            currentExtension == "GL_VERSION_4_0" ||
		    currentExtension == "GL_VERSION_4_1")
        {
            for (unsigned int i = 0; i < gl32extensions.size(); i++)
            {
                std::string curFunc = gl32extensions[i];
                std::string funcUp = curFunc;
                for (unsigned int n = 0; n < funcUp.length(); n++) funcUp[n] = toupper(funcUp[n]);
    		    fprintf(fpOutput, "        %s(%s) = (PFN%sPROC)GLH_EXT_GET_PROC_ADDRESS(\"%s\");\n", name_macro, curFunc.c_str(), funcUp.c_str(), curFunc.c_str());
	        	fprintf(fpOutput, "        if (NULL == %s(%s))\n", name_macro, curFunc.c_str());
    	    	fprintf(fpOutput, "            return GL_FALSE;\n");
            }
        }
        if (currentExtension == "GL_VERSION_4_0" ||
		    currentExtension == "GL_VERSION_4_1")
        {
            for (unsigned int i = 0; i < gl33extensions.size(); i++)
            {
                std::string curFunc = gl33extensions[i];
                std::string funcUp = curFunc;
                for (unsigned int n = 0; n < funcUp.length(); n++) funcUp[n] = toupper(funcUp[n]);
    		    fprintf(fpOutput, "        %s(%s) = (PFN%sPROC)GLH_EXT_GET_PROC_ADDRESS(\"%s\");\n", name_macro, curFunc.c_str(), funcUp.c_str(), curFunc.c_str());
	        	fprintf(fpOutput, "        if (NULL == %s(%s))\n", name_macro, curFunc.c_str());
    	    	fprintf(fpOutput, "            return GL_FALSE;\n");
            }
        }
        if (currentExtension == "GL_VERSION_4_1")
        {
            for (unsigned int i = 0; i < gl40extensions.size(); i++)
            {
                std::string curFunc = gl40extensions[i];
                std::string funcUp = curFunc;
                for (unsigned int n = 0; n < funcUp.length(); n++) funcUp[n] = toupper(funcUp[n]);
    		    fprintf(fpOutput, "        %s(%s) = (PFN%sPROC)GLH_EXT_GET_PROC_ADDRESS(\"%s\");\n", name_macro, curFunc.c_str(), funcUp.c_str(), curFunc.c_str());
	        	fprintf(fpOutput, "        if (NULL == %s(%s))\n", name_macro, curFunc.c_str());
    	    	fprintf(fpOutput, "            return GL_FALSE;\n");
            }
        }
        /** changes are made in this block */
	} else {
		if (opengl_core_names==1) {
			fprintf(fpOutput, "    /* These routines are prefixed by the preprocessor constant\n");
			fprintf(fpOutput, "       GLH_CORE_PREFIX to avoid colliding with the OpenGL 1.1 namespace. */\n");
		}
	}
	goto B;
B:
	if (GetToken(fpInput, token) == EOF) goto ERR;
	if (token[0] == '{') goto C;
	goto ERR;
C:
	if (GetToken(fpInput, token) == EOF) goto ERR;
	if (token[0] == '}') {
		/** changes are made in this block */

		if (mvscpp) {
			fprintf(fpOutput, "        return GL_TRUE;\n");
		} /* if (mvscpp) */

		/* obsolete?
		if (opengl_core_names) {
			fprintf (fpOutput, "#endif\n");
		}
		*/
	    fprintf(fpOutput, "#endif\n\n");
	    goto A;
		/** changes are made in this block */
	}
	strcpy(uprToken, token);
	for (i=0;uprToken[i]!='\0';i++) {
	  uprToken[i] = toupper(uprToken[i]);
	}
	tokenNamespace = GetNamespace(token);
	if (tokenNamespace == GLH_NAMESPACE_WGL) {
		fprintf(fpOutput, "# ifdef _WIN32\n");
	} else if (tokenNamespace == GLH_NAMESPACE_GLX) {
		fprintf(fpOutput, "# ifdef GLX_VERSION_1_3\n");
	}
	if (header) {
	    if (!footer) {
			fprintf(fpOutput, "    GLH_EXTERN PFN%sPROC %s(%s) GLH_INITIALIZER;\n", uprToken, name_macro, token);
	    } else {
			fprintf(fpOutput, "#define %s %s(%s)\n", token, name_macro, token);
	    }
	} else {
        if (currentExtension == "GL_VERSION_1_2")
            gl12extensions.push_back(token);
        if (currentExtension == "GL_VERSION_1_3")
            gl13extensions.push_back(token);
        if (currentExtension == "GL_VERSION_1_4")
            gl14extensions.push_back(token);
        if (currentExtension == "GL_VERSION_1_5")
            gl15extensions.push_back(token);
        if (currentExtension == "GL_VERSION_2_0")
            gl20extensions.push_back(token);
        if (currentExtension == "GL_VERSION_2_1")
            gl21extensions.push_back(token);
        if (currentExtension == "GL_VERSION_3_0")
            gl30extensions.push_back(token);
        if (currentExtension == "GL_VERSION_3_1")
            gl31extensions.push_back(token);
        if (currentExtension == "GL_VERSION_3_2")
            gl32extensions.push_back(token);
        if (currentExtension == "GL_VERSION_3_3")
            gl33extensions.push_back(token);
        if (currentExtension == "GL_VERSION_4_0")
            gl40extensions.push_back(token);
        if (currentExtension == "GL_VERSION_4_1")
            gl41extensions.push_back(token);

		fprintf(fpOutput, "        %s(%s) = (PFN%sPROC)GLH_EXT_GET_PROC_ADDRESS(\"%s\");\n", name_macro, token, uprToken, token);
		fprintf(fpOutput, "        if (NULL == %s(%s))\n", name_macro, token);
		fprintf(fpOutput, "            return GL_FALSE;\n");
	}
	if (tokenNamespace != GLH_NAMESPACE_GL) {
		fprintf(fpOutput, "# endif\n");
	}
	goto C;
FIN:
	if (header) {
	    fprintf(fpOutput, "\n");
	    if (footer)
		fprintf(fpOutput, "#endif\n");	    
	} else {
		/** changes are made in this block */
		if (mvscpp) {
			fprintf(fpOutput, "    }\n");
			fprintf(fpOutput, "    return GL_FALSE; /* requested extension not found */\n");
		} else { /* if (mvscpp) */
			/* comments added to output file */
			fprintf(fpOutput, "    } else {\n");
			fprintf(fpOutput, "        return GL_FALSE; /* requested extension not found */\n");
			fprintf(fpOutput, "    }\n");
			fprintf(fpOutput, "    return GL_TRUE; /* requested extension found and successfully loaded */\n");
		} /* if (mvscpp) */

		fprintf(fpOutput, "}\n");
		fprintf(fpOutput, "#endif\n\n");

#ifdef VIS_MSVC8CPP_EXT
		if (mvscpp) {
			fprintf(fpOutput, "#else /* (defined(__cplusplus) && defined(_MSC_VER)) */\n");
			fprintf(fpOutput, "/* END EDITED BY VIS 22.02.2007 */\n\n");
		} else { /* if (mvscpp) */
			fprintf(fpOutput, "/* BEGIN EDITED BY VIS 22.02.2007 */\n");
			fprintf(fpOutput, "#endif /* (defined(__cplusplus) && defined(_MSC_VER)) */\n");
			fprintf(fpOutput, "/* END EDITED BY VIS 22.02.2007 */\n\n");
#endif /* VIS_MSVC8CPP_EXT */

		fprintf(fpOutput, "#undef GLH_EXT_SINGLE_FILE\n\n");
		fprintf(fpOutput, "#ifdef __cplusplus\n");
		fprintf(fpOutput, "}\n");
		fprintf(fpOutput, "#endif\n\n");
		fprintf(fpOutput, "#endif /* GLH_GENEXT_H */\n");
#ifdef VIS_MSVC8CPP_EXT
		} /* if (mvscpp) */
#endif /* VIS_MSVC8CPP_EXT */
		/** changes are made in this block */
	}
	return 0;
ERR:
	printf("Error!\n");
	return 1;
}

int main(int argc, char** argv)
{
	FILE *fpInput, *fpOutput;
	char tmp1[] = "glh_genext.h";
	char tmp2[] = "extfile.txt";
	char* outputFilename = (argc > 1) ? argv[1] : tmp1;
	char* inputFilename = (argc > 2) ? argv[2] : tmp2;
	fpOutput = OpenFile(outputFilename, "w");

	/* Parse file for header portion */
	fpInput = OpenFile(inputFilename, "r");
	ParseFile(fpInput, fpOutput, 1,0,0);
	fclose(fpInput);

	/* Parse file again for code portion */

#ifdef VIS_MSVC8CPP_EXT
	fprintf(fpOutput, "/* BEGIN EDITED BY VIS 22.02.2007 */\n");
	fprintf(fpOutput, "#if (defined(__cplusplus) && defined(_MSC_VER))\n");

	fpInput = OpenFile(inputFilename, "r");
	ParseFile(fpInput, fpOutput, 0,0,1);
	fclose(fpInput);
#endif /* VIS_MSVC8CPP_EXT */

	fpInput = OpenFile(inputFilename, "r");
	ParseFile(fpInput, fpOutput, 0,0,0);
	fclose(fpInput);

	fpInput = OpenFile(inputFilename, "r");
	ParseFile(fpInput, fpOutput, 1,1,0);
	fclose(fpInput);

	fclose(fpOutput);

	return 0;
}
